class HyppoEngine\DTO as "DTO\nuses DTO,Factory"{
}

package HyppoEngine\DTO\ {
    class HyppoEngine\DTO\Document as "Document"{
    }

    package HyppoEngine\DTO\Document\ {
        class HyppoEngine\DTO\Document\Author as "Author" {
        }
        HyppoEngine\DTO\Document\Author -up-|> HyppoEngine\DTO
    }
    HyppoEngine\DTO\Document -down-o HyppoEngine\DTO\Document\Author

    HyppoEngine\DTO\Document -up-|> HyppoEngine\DTO

    class HyppoEngine\DTO\RepositoryNode as "RepositoryNode" {
    }
    HyppoEngine\DTO\RepositoryNode -up-|> HyppoEngine\DTO

    class HyppoEngine\DTO\SyntaTree as "SyntaxTree" {
    }
}



