class HyppoEngine\Parser as "Parser" {
}
HyppoEngine\Parser .up.> HyppoEngine\Exception

package HyppoEngine\Parser\ {
    class HyppoEngine\Parser\Bnf as "Bnf" {
    }
    HyppoEngine\Parser\Bnf -up-|> HyppoEngine\Parser

}



