class HyppoEngine\Render as "Render\nuses Factory" {
}

HyppoEngine\Render .up.> HyppoEngine\Exception


package HyppoEngine\Render\ {
    class HyppoEngine\Render\Html as "Html" {
    }
    HyppoEngine\Render\Html -up-|> HyppoEngine\Render
}






