package HyppoEngine\Trait {
    class HyppoEngine\Trait\Attribute as "Attribute" {
    }
    package HyppoEngine\Trait\Pattern\ {
        class HyppoEngine\Trait\Pattern\Builder as "Builder" {
        }
        class HyppoEngine\Trait\Pattern\Factory as "Facroty" {
        }
        class HyppoEngine\Trait\Pattern\DTO as "DTO" {
        }
        class HyppoEngine\Trait\Pattern\Repository as "Reposiroty" {
        }
        HyppoEngine\Trait\Pattern\Repository -left-> HyppoEngine\Trait\Attribute
        
        HyppoEngine\Trait\Pattern\Builder .. HyppoEngine\Trait\Pattern\Factory
        HyppoEngine\Trait\Pattern\Factory .. HyppoEngine\Trait\Pattern\DTO
        HyppoEngine\Trait\Pattern\DTO .. HyppoEngine\Trait\Pattern\Repository
    }

}



