<root>::=<Header><Body>
<root>::=<Body>

<Line>::=/.*\n/

<Header>::=<Line><HeaderDelimiter>

<HeaderDelimiter>::=/=+\n/

<Body>::={<Section>}
<Body>::={<Line>}

<Section>::=<Section1>
<Section>::=<Section2>
<Section>::=<Section3>
<Section>::=<Section4>
<Section>::=<Section5>
<Section>::=<Section6>
