<Spaces>::=/\s+/
<Break>::=/{{break}}/
<Letter>:=/./
<HeaderDelimiter>::=/^=+\n$/

<Letters>:=<Letter>
<Letters>:=<Letter><Letters>
<Letters>:=//

<Breaks>:=<Break>
<Breaks>::=<Break><Breaks>

<Lines>::=<Letters><Break><Lines>
<Letters>::=<Letters><MarkUp><Letters>

<root>::=<Header><Lines>
<root>::=<Lines>

<Header>::=<Letters><Break><HeaderDelimiter><Break>

<MarkUp>::=<Section>

<Section>::=<Break><SectionCaption><Breaks><SectionBody>
<SectionBody>:=<Letters>

<SectionCaption>::=<SectionMarker><Spaces><Letters>

<SectionMarker>:=/\#+/

<SectionBody>::=<Letters>